// <auto-generated />
using System;
using DEAApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEAApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DEAModels.Administrator", b =>
                {
                    b.Property<int>("IdAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdAdministrator");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("DEAModels.Competition", b =>
                {
                    b.Property<int>("IdCompetition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCountry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFederation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCompetition");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdFederation");

                    b.HasIndex("IdSeason");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("DEAModels.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCountry");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DEAModels.Federation", b =>
                {
                    b.Property<int>("IdFederation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCountry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdFederation");

                    b.HasIndex("IdCountry");

                    b.ToTable("Federations");
                });

            modelBuilder.Entity("DEAModels.League", b =>
                {
                    b.Property<int>("IdLeague")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCountry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdLeague");

                    b.HasIndex("IdCountry");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("DEAModels.LeagueTable", b =>
                {
                    b.Property<int>("IdLeagueTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTeam")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchesDrawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdLeagueTable");

                    b.HasIndex("IdSeason");

                    b.HasIndex("IdTeam");

                    b.ToTable("LeagueTables");
                });

            modelBuilder.Entity("DEAModels.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAwayTeam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCompetition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdHomeTeam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStadium")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonIdSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMatch");

                    b.HasIndex("IdAwayTeam");

                    b.HasIndex("IdCompetition");

                    b.HasIndex("IdHomeTeam");

                    b.HasIndex("IdStadium");

                    b.HasIndex("SeasonIdSeason");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DEAModels.MatchPlayer", b =>
                {
                    b.Property<int>("IdMatchPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPosition")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubstitutionMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YellowCards")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMatchPlayers");

                    b.HasIndex("IdMatch");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdPosition");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("DEAModels.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Height")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTeam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MarketValue")
                        .IsRequired()
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Weight")
                        .IsRequired()
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdPlayer");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdPosition");

                    b.HasIndex("IdTeam");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DEAModels.Position", b =>
                {
                    b.Property<int>("IdPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPosition");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("DEAModels.Season", b =>
                {
                    b.Property<int>("IdSeason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdLeague")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMatchdays")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSeason");

                    b.HasIndex("IdLeague");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("DEAModels.Stadium", b =>
                {
                    b.Property<int>("IdStadium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdStadium");

                    b.HasIndex("IdTeam")
                        .IsUnique();

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("DEAModels.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCompetition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCountry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLeague")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTeam");

                    b.HasIndex("IdCompetition");

                    b.HasIndex("IdCountry");

                    b.HasIndex("IdLeague");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DEAModels.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DEAModels.Competition", b =>
                {
                    b.HasOne("DEAModels.Country", "Country")
                        .WithMany("Competitions")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Federation", "Federation")
                        .WithMany("Competitions")
                        .HasForeignKey("IdFederation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Season", "Season")
                        .WithMany("Competitions")
                        .HasForeignKey("IdSeason")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Federation");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DEAModels.Federation", b =>
                {
                    b.HasOne("DEAModels.Country", "Country")
                        .WithMany("Federations")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DEAModels.League", b =>
                {
                    b.HasOne("DEAModels.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DEAModels.LeagueTable", b =>
                {
                    b.HasOne("DEAModels.Season", "Season")
                        .WithMany("LeagueTables")
                        .HasForeignKey("IdSeason")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Team", "Team")
                        .WithMany()
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DEAModels.Match", b =>
                {
                    b.HasOne("DEAModels.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("IdAwayTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("IdCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("IdHomeTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Stadium", "Stadium")
                        .WithMany("Matches")
                        .HasForeignKey("IdStadium")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Season", null)
                        .WithMany("Matches")
                        .HasForeignKey("SeasonIdSeason");

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("DEAModels.MatchPlayer", b =>
                {
                    b.HasOne("DEAModels.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("IdMatch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Position", "Position")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("IdPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DEAModels.Player", b =>
                {
                    b.HasOne("DEAModels.Country", "Country")
                        .WithMany("Players")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("IdPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DEAModels.Season", b =>
                {
                    b.HasOne("DEAModels.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("IdLeague")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("DEAModels.Stadium", b =>
                {
                    b.HasOne("DEAModels.Team", "Team")
                        .WithOne("Stadium")
                        .HasForeignKey("DEAModels.Stadium", "IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DEAModels.Team", b =>
                {
                    b.HasOne("DEAModels.Competition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("IdCompetition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEAModels.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("IdLeague")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Country");

                    b.Navigation("League");
                });

            modelBuilder.Entity("DEAModels.Competition", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DEAModels.Country", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Federations");

                    b.Navigation("Leagues");

                    b.Navigation("Players");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DEAModels.Federation", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("DEAModels.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("DEAModels.Match", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DEAModels.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DEAModels.Position", b =>
                {
                    b.Navigation("MatchPlayers");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("DEAModels.Season", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("LeagueTables");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DEAModels.Stadium", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DEAModels.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");

                    b.Navigation("Stadium");
                });
#pragma warning restore 612, 618
        }
    }
}
